name: Playwright Tests
on:
  push:
    branches: [ "Master" ]
  pull_request:
    branches: [ "Master" ]
jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 
        
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build & Install
      run: dotnet build --configuration Debug

      # Step 7: Install Allure Commandline
    - name: Install Allure CLI
      run: npm install -g allure-commandline --save-dev
      
    - name: install browsers
      run: pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps

    

    - name: Create Results Directory
      run: |
        mkdir allure-results
      
    - name: Run tests
      run: dotnet test --configuration Debug --settings e2e.runsettings  --logger "trx;LogFileName=test-results.trx" --results-directory "allure-results"


        # Step 6: Install Allure
    - name: Install Allure
      run: scoop install allure
     

 # Step 7: Generate Allure Results
    - name: Generate Allure Results
      run: |
        mkdir allure-results
        allure generate ./TestResults -o allure-results --clean

    # Step 8: Upload Allure History
    - name: Upload Allure History
      uses: actions/upload-artifact@v3
      with:
        name: allure-history
        path: allure-results/history

    # Step 9: Upload Allure Report
    - name: Publish Allure Report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-results








        
    # - name: Load test report history
    #   uses: actions/checkout@v3
    #   if: always()
    #   continue-on-error: true
    #   with:
    #     ref: gh-pages
    #     path: gh-pages

    # - name: Generate Allure Report
    #   run: |
    #     allure generate allure-results --clean -o allure-report
    #   if: always()
      

    # # - name: Allure Report action from marketplace.
    # #   uses: simple-elf/allure-report-action@master
    # #   if: always()
     

    # - name: Publish test report
    #   uses: peaceiris/actions-gh-pages@v3
    #   if: always()
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_branch: gh-pages
    #     publish_dir: allure-history
