name: Playwright Tests
on:
  push:
    branches: [ "Master" ]
  pull_request:
    branches: [ "Master" ]
jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 
        
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build & Install
      run: dotnet build --configuration Debug

    - name: Install Allure CLI
      run: npm install -g allure-commandline --save-dev
      
    - name: install browsers
      run: pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps

    
    - name: Run tests
      run: |
        mkdir allure-results
        dotnet test --settings e2e.runsettings  --logger "allure;LogDirectory=allure-results" --results-directory "allure-results"
      continue-on-error: true

    - name: Generate Allure Report
      if: always()
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Upload Allure Report Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report

    - name: Deploy report to Github Pages (manual git)
      if: always()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git clone --branch gh-pages --single-branch https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
        robocopy allure-report gh-pages /E
        cd gh-pages
        git add .
        git commit -m "Update Allure report [skip ci]" || exit 0
        git push
