name: Playwright Tests
on:
  push:
    branches: [ "Master" ]
  pull_request:
    branches: [ "Master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 
    
    # - name: Install rsync and refresh environment
    #   shell: powershell
    #   run: |
    #     choco install rsync -y
    #     Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
    #     refreshenv
        
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build & Install
      run: dotnet build --configuration Debug

      # Step 7: Install Allure Commandline
    - name: Install Allure CLI
      run: npm install -g allure-commandline --save-dev
      
    - name: install browsers
      run: pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps

    
    - name: Run tests
      run: |
        mkdir allure-results
        dotnet test --settings e2e.runsettings  --logger "trx;LogFileName=allure-report.trx" --results-directory "allure-results"
      continue-on-error: true
    
    - name: Install scoop (Windows)
      uses: MinoruSekine/setup-scoop@v4.0.1
      if: steps.restore_cache.outputs.cache-hit != 'true'
      with:
        install_scoop: 'true'
        buckets: extras
        apps: ${{ env.packages_to_install }}
        scoop_update: 'true'
        update_path: 'true'

    # Step 6: Install Allure
    - name: Download Allure CLI
      run: scoop install allure

      
    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: build/allure-results

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
